#include "../extern/midifile/include/MidiFile.h"
#include "RtMidi.h"
#include "SDL.h"
#include "SDL_image.h"
#include "SDL_mixer.h"
#include "SDL_ttf.h"
#include "absl/container/flat_hash_map.h"
#include "absl/container/flat_hash_set.h"
#include "absl/container/node_hash_map.h"
#include "absl/hash/hash.h"
#include "absl/strings/ascii.h"
#include "absl/strings/match.h"
#include "absl/strings/str_replace.h"
#include "absl/strings/str_split.h"
#include "absl/types/span.h"
#include "flatbuffers/flatbuffers.h"
#include "flatbuffers/idl.h"
#include "flatbuffers/minireflect.h"
#include "fmt/format.h"
#include "magic_enum.hpp"
#include "nonstd/expected.hpp"
#include "observer-ptr/observer-ptr.hpp"
#include "range/v3/action/sort.hpp"
#include "range/v3/algorithm/any_of.hpp"
#include "range/v3/algorithm/find.hpp"
#include "range/v3/algorithm/for_each.hpp"
#include "range/v3/algorithm/reverse.hpp"
#include "range/v3/all.hpp"
#include "range/v3/distance.hpp"
#include "range/v3/numeric/accumulate.hpp"
#include "range/v3/view/all.hpp"
#include "range/v3/view/concat.hpp"
#include "range/v3/view/cycle.hpp"
#include "range/v3/view/drop.hpp"
#include "range/v3/view/drop_while.hpp"
#include "range/v3/view/enumerate.hpp"
#include "range/v3/view/filter.hpp"
#include "range/v3/view/group_by.hpp"
#include "range/v3/view/intersperse.hpp"
#include "range/v3/view/iota.hpp"
#include "range/v3/view/join.hpp"
#include "range/v3/view/map.hpp"
#include "range/v3/view/remove_if.hpp"
#include "range/v3/view/reverse.hpp"
#include "range/v3/view/sliding.hpp"
#include "range/v3/view/take.hpp"
#include "range/v3/view/take_while.hpp"
#include "range/v3/view/transform.hpp"
#include "range/v3/view/zip.hpp"
#include "tl/function_ref.hpp"
#include "ucl++.h"

// clang-format off
//#include "spdlog/spdlog.h"
//#include "spdlog/sinks/stdout_color_sinks.h"
// clang-format on

#include <stdio.h>
#include <algorithm>
#include <array>
#include <cctype>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <deque>
#include <exception>
#include <experimental/filesystem>
#include <fstream>
#include <functional>
#include <iterator>
#include <limits>
#include <list>
#include <memory>
#include <mutex>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <scelta.hpp>
#include <set>
#include <stdexcept>
#include <string>
#include <string_view>
#include <thread>
#include <tuple>
#include <type_traits>
#include <typeinfo>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>
